camunda:
  client:
    mode: self-managed

operate:
  client:
    base-url: http://localhost:8081
    username: demo
    password: demo

camunda7:
  client:
    base-url: http://localhost:8082
    rest-api-context: engine-rest
    check-on-init: true
