operate.client:
  url: http://localhost:8081
  authentication:
    simple:
      username: demo
      password: demo

zeebe:
  client:
    security:
      plaintext: true
    broker:
      gateway-address: localhost:26500

server.port: 8090